---
abstract: 'time stamped log file'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ gmail.comE<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Stamped
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  File::Stamped:
    file: lib/File/Stamped.pm
    version: 0.03
requires:
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
