---
abstract: 'time stamped log file'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Stamped
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  File::Stamped:
    file: lib/File/Stamped.pm
    version: 0.07
requires:
  perl: 5.008001
resources:
  bugtracker: https://github.com/tokuhirom/File-Stamped/issues
  homepage: https://github.com/tokuhirom/File-Stamped
  repository: git://github.com/tokuhirom/File-Stamped.git
version: 0.07
x_contributors:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
  - 'Kan Fushihara <kan.fushihara@gmail.com>'
